### ISSUE TITLE
Set root to be other than process.cwd()

### ISSUE THREAD

**Issue by salemhilal** [bengourley/find-nearest-file#2]
It would be useful to be able to set the root directory to start traversal from. For example, I'm writing a plugin for Atom, and if the editor isn't launched from the command line, process.cwd() is always '/', not the directory of anything useful.

If you'd like, I can submit a PR.

**Comment by bengourley** [comment]
Hi, sorry I only just saw this. Sounds reasonable, I'd accept a PR for this. Cheers.

**Comment by callumlocke** [comment]
+1

**Comment by bengourley** [comment]
Fixed by #3.

**Comment by salemhilal** [comment]
Thank you!
